### ISSUE TITLE
'QuantizedLinear' object has no attribute 'weight' error

### ISSUE THREAD

**Issue by fahadh4ilyas** [Vahe1994/AQLM#31]
I'm trying to do quantization with this parameters:

```bash
python main.py ../models/my-mistral-7B wikitext2 --nsamples=1024 --num_codebooks=1 --nbits_per_codebook=16 --in_group_size=8 --relative_mse_tolerance=0.01 --finetune_relative_mse_tolerance=0.001 --finetune_batch_size=32 --local_batch_size=1 --save ../models/my-mistral-7B-AQLM --model_seqlen 8192 --offload_activations
```

and I got this error

```python
Traceback (most recent call last):
  File "/home/fahadh/AQLM/main.py", line 779, in <module>
    quantize_model(model, args)
  File "/home/fahadh/AQLM/main.py", line 48, in quantize_model
    results = quantize_aq(model, dataloader, args)
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/fahadh/AQLM/main.py", line 252, in quantize_aq
    layer = finetune_groupwise(layer=layer, inps=inps, outs=outs, args=args, **forward_args)
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/fahadh/AQLM/src/finetune.py", line 105, in finetune_groupwise
    loss = _compute_mse_parallel(
  File "/home/fahadh/AQLM/src/finetune.py", line 224, in _compute_mse_parallel
    mse_components = torch.nn.parallel.parallel_apply(
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
  File "/home/fahadh/AQLM/src/finetune.py", line 201, in _compute_mse_on_batch
    outs_prediction, *_unused = layer(inps_batch, **kwargs)
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/transformers/models/mistral/modeling_mistral.py", line 754, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/transformers/models/mistral/modeling_mistral.py", line 437, in forward
    target_dtype = self.q_proj.weight.dtype
  File "/home/fahadh/anaconda3/envs/aqlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'QuantizedLinear' object has no attribute 'weight'
```

This happens after fine tuning layers 0 of mistral model. Here is what printed before the error

```python
PREPARING TO FINETUNE
MistralDecoderLayer(
  (self_attn): MistralFlashAttention2(
    (q_proj): QuantizedLinear(
      (quantized_weight): QuantizedWeight(self.out_features=4096, self.in_features=4096, bits_per_parameter=2.50390625)
    )
    (k_proj): QuantizedLinear(
      (quantized_weight): QuantizedWeight(self.out_features=1024, self.in_features=4096, bits_per_parameter=4.00390625)
    )
    (v_proj): QuantizedLinear(
      (quantized_weight): QuantizedWeight(self.out_features=1024, self.in_features=4096, bits_per_parameter=4.00390625)
    )
    (o_proj): QuantizedLinear(
      (quantized_weight): QuantizedWeight(self.out_features=4096, self.in_features=4096, bits_per_parameter=2.50390625)
    )
    (rotary_emb): MistralRotaryEmbedding()
  )
  (mlp): MistralMLP(
    (gate_proj): QuantizedLinear(
      (quantized_weight): QuantizedWeight(self.out_features=14336, self.in_features=4096, bits_per_parameter=2.146763392857143)
    )
    (up_proj): QuantizedLinear(
      (quantized_weight): QuantizedWeight(self.out_features=14336, self.in_features=4096, bits_per_parameter=2.146763392857143)
    )
    (down_proj): QuantizedLinear(
      (quantized_weight): QuantizedWeight(self.out_features=4096, self.in_features=14336, bits_per_parameter=2.1439732142857144)
    )
    (act_fn): SiLU()
  )
  (input_layernorm): MistralRMSNorm()
  (post_attention_layernorm): MistralRMSNorm()
)
Fine-tuning 3721216 parameters
```

**Comment by BlackSamorez** [comment]
Hi @fahadh4ilyas ! 
Honestly, we haven't tried running Mistral in a while so there might be errors like that.
It looks like the `mistral` implementation from `transformers` does a very straightforward `dtype` check that we aren't handling well.
May I ask you to checkout into the [pre_quantization_dtype](https://github.com/Vahe1994/AQLM/tree/pre_quantization_dtype) branch and try again. It should probably fix the issue. Please let us know if it works.

**Comment by fahadh4ilyas** [comment]
I found the problem. I tried to load model using flash attention implementation because I thought it would be faster. But, inside the flash attention implementation of transformers, there is a process to cast the result from attention from float32 back to projection type (float16) hence why the need to check dtype of weight. Reverting loading model without flash attention solve this problem.
