### ISSUE TITLE
AttributeError: module 'torch.library' has no attribute 'impl_abstract'

### ISSUE THREAD

**Issue by mgoin** [Vahe1994/AQLM#42]
Note: I tested this for aqlm==1.0.3 and 1.1.0

I'm having issue trying to run inference with a HF model in Transformers

```
pip install transformers aqlm[gpu,cpu]
```

Pytorch 2.1.2 is installed

Then
```python
from transformers import AutoTokenizer, AutoModelForCausalLM
quantized_model = AutoModelForCausalLM.from_pretrained("ISTA-DASLab/Llama-2-7b-AQLM-2Bit-1x16-hf", torch_dtype="auto", device_map="cuda").cuda()
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mixtral-8x7B-v0.1")
output = quantized_model.generate(tokenizer("", return_tensors="pt")["input_ids"].cuda(), max_new_tokens=10)
print(output)
```

Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1544, in generate
    return self.greedy_search(
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2404, in greedy_search
    outputs = self(
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1168, in forward
    outputs = self.model(
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1008, in forward
    layer_outputs = decoder_layer(
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 734, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 633, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/aqlm/inference.py", line 70, in forward
    self.prepare_matmul_op(input)
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/aqlm/inference.py", line 86, in prepare_matmul_op
    get_forward_pass_kernel(self.codebooks, False),
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/aqlm/inference_kernels/kernel_selector.py", line 35, in get_forward_pass_kernel
    from .cuda_kernel import CUDA_FOLDER
  File "/home/michael/venvs/nm-vllm/lib/python3.10/site-packages/aqlm/inference_kernels/cuda_kernel.py", line 20, in <module>
    @torch.library.impl_abstract("aqlm::code1x16_matmat")
AttributeError: module 'torch.library' has no attribute 'impl_abstract'
```

**Comment by BlackSamorez** [comment]
Well, it's definitely [out there](https://pytorch.org/docs/stable/library.html#torch.library.impl_abstract) and everything was ever tested on `torch==2.1.2` and worked fine.
Could you try and reinstall `pytorch` to make sure that your installation is valid?

**Comment by mgoin** [comment]
@BlackSamorez thanks for the response - are you sure you've tested `torch==2.1.2`? This clearly hasn't worked for me and when I go to the [pytorch 2.1 docs](https://pytorch.org/docs/2.1/library.html#torch.library.impl_abstract), impl_abstract doesn't seem to exist. I just found out that if I install `torch==2.2.0` then it works fine, so maybe it's worth updating the minimum pytorch version?

**Comment by BlackSamorez** [comment]
Sorry, you're right, it doesn't work for `pytorch==2.1.2` and lower. My pip+conda env has been hiding the real version from me.
Looks like we'll have to update the requirements after all.
Many thanks!
