### ISSUE TITLE
Aqlm models cannot be trained in parallel.

### ISSUE THREAD

**Issue by Minami-su** [Vahe1994/AQLM#59]
```
ACCELERATE_LOG_LEVEL=info accelerate launch --config_file deepspeed_zero2-sft.yaml --num_processes=1 ft-4bit-freedom-2bit.py \
    --base_model 'Mixtral-8x7B-Instruct-v0_1-AQLM-2Bit-1x16-hf' \
    --data_path 'eval_set_IA_multi_dialog3_sft.json' \
    --output_dir 'eval_set_IA_multi_dialog3_sft' \
    --batch_size 1 \
    --micro_batch_size 1 \
    --num_epochs 1 \
    --learning_rate 5e-4 \
    --cutoff_len 1024 \
    --val_set_size 0 \
    --lora_r 32 \
    --lora_alpha 32 \
    --lora_dropout 0.1 \
    --train_on_inputs \
    --group_by_length

```

```
Traceback (most recent call last):
  File "/home/luhao/alpaca-2bit-sft/ft-4bit-freedom-2bit.py", line 345, in <module>
    fire.Fire(train)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/luhao/alpaca-2bit-sft/ft-4bit-freedom-2bit.py", line 336, in train
    trainer.train()
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/transformers/trainer.py", line 1933, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/accelerate/accelerator.py", line 1255, in prepare
    result = self._prepare_deepspeed(*args)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/accelerate/accelerator.py", line 1640, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/deepspeed/__init__.py", line 176, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
    self._configure_distributed_model(model)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1157, in _configure_distributed_model
    self._broadcast_model()
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1077, in _broadcast_model
    dist.broadcast(p.data, groups._get_broadcast_src_rank(), group=self.seq_data_parallel_group)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 205, in broadcast
    return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1914, in broadcast
    work = group.broadcast([tensor], opts)
TypeError: Input tensor data type is not supported for NCCL process group: Short
```

**Comment by BlackSamorez** [comment]
Hi! NCCL really doesn't work with `int16` for some reason.
One thing you could do is try to manually cast every `int16` parameter to `int32` before the broadcast and back to `int16` after. I'm not sure if `deepspeed`/`accelerate` allow for such kind of custom preprocessing.
Or, maybe, you could cast every `int16` parameter to `int32` before the broadcast and modify the `QuantizedLinear` forward pass to cast back on the first pass.

**Comment by Vahe1994** [comment]
> It's bf16 now,do you mean fp32?

AQLM  stores weights as codes in int16 and codebooks in fp16 (or bf16). I would recommend trying both converting codes from int16 to int32 and changing the codebooks data type from fp16 (or bf16) to float32 and see if it helps.
